### ISSUE TITLE
Possible memory leak in setObjectForKey

### ISSUE THREAD

**Issue by Vestrit** [johnezang/JSONKit#10]
aKey = [ aKey copy ]; Looks like it could be leaking.  We created about 30 objects then released them and ended up with a much larger footprint than we should have had in quick check.

Also in several places where you do anObject = [ anObject retain ];  should probably be [ anObject retain ]; since the assignment is technically considered "dead code" by the static analyzer.

**Comment by johnezang** [comment]
Sending the key a `copy` message is correct- that is what dictionaries are supposed to do to obtain an immutable version of the key.

Why do you think it's leaking?  Does `leaks` or the Instruments leaks tool report that the memory has been leaked?

**Comment by johnezang** [comment]
Commit johnezang/JSONKit@f520db76dab3d5aa7b8ca1d581e8c7fc6ece2819 adds a `#ifndef __clang_analyzer__` around the `copy` and `release` bits to silence the analyzer.

**Comment by johnezang** [comment]
I'm going to close this ticket since I have been unable to reproduce any memory leaks, and `clang` just seems to be whining about non-issues once again (though thankfully silenced with `#ifndef __clang_analyzer__`).
