### ISSUE TITLE
objectFromJSONString has a bug: "priceLogTrend": -9.3,--->priceLogTrend = "-9.300000000000001";

### ISSUE THREAD

**Issue by evoloyeu** [johnezang/JSONKit#110]
json string:
"priceLogTrend": -9.3,

parsed result:
priceLogTrend = "-9.300000000000001";

the expected result :
priceLogTrend = -9.3;

**Comment by evoloyeu** [comment]
numbers are parsed to strings

and some number is parsed with weird error.

like :

"priceLogTrend": -9.3,--->priceLogTrend = "-9.300000000000001";

what I want is  "priceLogTrend": -9.3, --->  priceLogTrend = -9.3;

**Comment by johnezang** [comment]
This is not a bug.  The "problem" is due to the fact that the value `9.3` can not be represented exactly using a IEEE 754 floating point number.

From the README.md documentation:

> The C `double` primitive type, or IEEE 754 Double 64-bit floating-point, is used to represent floating-point JSON Number values.  JSON that contains floating-point Number values that can not be represented as a `double` (i.e., due to over or underflow) will fail to parse and optionally return a `NSError` object.  The function `strtod()` is used to perform the conversion.  Note that the JSON standard does not allow for infinities or `NaN` (Not a Number).  The conversion and manipulation of [floating-point values is non-trivial](http://www.validlab.com/goldberg/paper.pdf).  Unfortunately, RFC 4627 is silent on how such details should be handled.  You should not depend on or expect that when a floating-point value is round tripped that it will have the same textual representation or even compare equal.  This is true even when JSONKit is used as both the parser and creator of the JSON, let alone when transferring JSON between different systems and implementations.

**Comment by icoco** [comment]
my solution is : 
1) convert the double value to NSString 
2) convert the string to NSDecimalNumber but NSNumber. 

then it will normal , eg: 883.04 will not be 883.0399999999

that is crazy in my view .

**Comment by icoco** [comment]
anyone ?
