### ISSUE TITLE
Handling Unicode chars like \U2019

### ISSUE THREAD

**Issue by loretoparisi** [johnezang/JSONKit#111]
Hi I have a Web Service whose response is "octet-stream". I cannot change the response header. The content was sent with a json encoded by JSONKit (through a HTTP POST).

When I try to read the content I got bad Unicode escaping like for characters \U2019 or the following:

text = "but here\U00e2\U0080\U0099s my number";

I inizialized JSONKit as 

self.decoder=[JSONDecoder decoderWithParseOptions:JKSerializeOptionNone]; // json decoder

Any idea this happens ?

**Comment by Bo98** [comment]
You should be passing a parse option into `JSONDecoder`, not a serialize option. You probably only want/need `JKParseOptionNone` which is synonymous with `JKParseOptionStrict`. This is also the default so you don't need to even specify this and just use `[JSONDecoder decoder]`.

**Comment by loretoparisi** [comment]
Thanks. Fixed.
