### ISSUE TITLE
JSONKit does not compile in Release mode

### ISSUE THREAD

**Issue by ngoccuong291** [johnezang/JSONKit#112]
To whom it may concern

I tried to use RestKit with Cocoapods and JSONKit seems to be one of the dependencies.
The problem is when I tried to build in Release mode this line broke:

(line 920 in JSONKit.m)
NSCParameterAssert((oldCount == dictionary->count));

Because in Release mode, the NS_BLOCK_ASSERTIONS did not get defined and this line did not get executed:

NSUInteger oldCount = dictionary->count;

**Comment by ryanmaxwell** [comment]
+1

solution is to wrap line 920

```
#ifndef NS_BLOCK_ASSERTIONS
      NSCParameterAssert((oldCount == dictionary->count));
#endif
```

**Comment by ngoccuong291** [comment]
Thanks, that worked but I had to attached JSONKit into my project and moved it out of Cocoapods
