### ISSUE TITLE
Possible performance regression

### ISSUE THREAD

**Issue by omarkilani** [johnezang/JSONKit#12]
Hi John,

Not really a big deal and I'm not sure if this is related to the recent JKSerializer class, but I'm finding that encodes are 10-20% slower than my last test (with commit 524b9d78d3a0e68d3376).

Do you see a similar drop?

Regards,
Omar

**Comment by johnezang** [comment]
No, I did not see any performance regressions.  I typically do my testing on the `x86_64` architecture using `gcc-4.2 -DNS_BLOCK_ASSERTIONS -O2`.

What architecture did you see the performance drop on?  Did you use `-DNS_BLOCK_ASSERTIONS`?  What optimization level?

**Comment by omarkilani** [comment]
Hey John,

I forgot to define -DNS_BLOCK_ASSERTIONS while testing. :)

Sorry for the false alarm. Please close with an "Idiocy" label. :)

Keep up the awesome work on all your *Kits (I'd love to see TransactionKit resurrected one day. :)

Regards,
Omar

**Comment by johnezang** [comment]
Well I'm glad to hear that it wasn't an actual problem, as I really hoped to keep the `JKSerializer` object paradigm as it makes some things easier that I'm experimenting with.  In particular, having an autoreleased object wrapper makes it easier to track resources and ensure they are released "no matter what"... like say if you added the ability for the user to "format" unhandled classes (i.e., `NSDate`), and the users code wasn't terribly careful and threw exceptions and what not.  :)

As for TransactionKit... yea, that's a much, _much_ more "interesting" project, but  interesting and "lots of people use and like" aren't the same thing, or even remotely correlated.  :)
