### ISSUE TITLE
JSONString and NSNumbers 

### ISSUE THREAD

**Issue by ssteinberg** [johnezang/JSONKit#13]
Encoding a dictionary with some NSNumbers gives me a JSON with all values ".17g". I have no idea what it means. Code:

```
NSMutableDictionary *json = [NSMutableDictionary dictionary];
[json setObject:n2 forKey:@"n2"];
[json setObject:n1 forKey:@"n1"];

NSError *error=nil;
NSString *p=[json JSONStringWithOptions:JKSerializeOptionNone error:&error];
NSLog(@"JSON: %@ %f %f",p,[n1 doubleValue],[n2 doubleValue]);
```

JSON output: '{"n2":.17g,"n1":.17g}'. No error.

LLVM GCC 4.2 with XCode 4. Debug build, no optimizations.

**Comment by johnezang** [comment]
The only way I can possibly think of that would cause this is that you somehow managed to remove the `%` in the following line:

``` objective-c
return(jk_encode_printf(encodeState, cacheSlot, startingAtIndex, encodeCacheObject, "%.17g", dv));
```

You can search for `jk_encode_printf`, as it only appears about six times in the source.  I suspect when you get down the the numbers handling section, you'll find that the `%` vanished somehow.

**Comment by ssteinberg** [comment]
Thanks. I was using experimental branch. Switching to stable was enough. No idea if and how the % vanished, I didn't touch the source.

**Comment by johnezang** [comment]
Ah, when I checked the experimental branch, it was missing the `%`.  I think it got munged during a commit.  I've merged the experimental branch with master and fixed this problem.
