### ISSUE TITLE
the app references non-public selectors in payload startIndex

### ISSUE THREAD

**Issue by andrewstephenson-v1** [johnezang/JSONKit#136]
so called 'private API' detected on submitting an iOS7 app update to the AppStore

**Comment by andrewstephenson-v1** [comment]
ah, maybe something else.. excuse me, I have my 'must submit for iOS7 day 1' panic pants on

**Comment by imoreapps** [comment]
Did you find the solution?

**Comment by andrewstephenson-v1** [comment]
Turns out there's a clash of selector name in sharekit, specifically related to Google Oauth. Have raised an issue over there.

```
Sorry for the panic :)

—
```

**Comment by imoreapps** [comment]
Thanks for your quick reply. Do you mean this is an issue of google-api-objectivec-client library?

**Comment by imoreapps** [comment]
Below link is about the issue.

https://code.google.com/p/google-api-objectivec-client/issues/detail?id=46&q=startIndex
