### ISSUE TITLE
objectWithData Snippet

### ISSUE THREAD

**Issue by loretoparisi** [johnezang/JSONKit#16]
Hello,
could you please show a snippet of basic decoding with objectWithData? thanks

I'm using the following code

```
self.decoder=[JSONDecoder decoderWithParseOptions:JKSerializeOptionNone];

NSError *error = nil;
NSObject *jsonObj = [decoder objectWithData:data error:&error];
if (data == nil || error) { // parsing or data error
    [self handleError:error];
    return;
}

// TODO: do something with NSObject
```

**Comment by johnezang** [comment]
I'm not sure I understand the request.  The example you provided is "a snippet of basic decoding with objectWithData".   Or are you asking for an example of "what to do with `jsonObj`"?

**Comment by loretoparisi** [comment]
Hello,
I finally realized how to use your wonderful lib:

// mapping iTunes Search API JSON
int results = [[jsonObject valueForKey:@"resultCount"] intValue];
    NSLog(@"results %d",results);
    if(results >0) { // has results
        NSArray *results = [jsonObject valueForKey:@"results"];
        for(NSObject *aResult in results) {
            NSString *wrapperType = [aResult valueForKey:@"wrapperType"];
            NSString *kind = [aResult valueForKey:@"kind"];
            if([wrapperType isEqualToString:@"track"] && [kind isEqualToString:@"song"]) {
                NSString *title = [aResult valueForKey:@"trackName"];
                NSString *artistName = [aResult valueForKey:@"artistName"];
                NSString *previewUrl = [aResult valueForKey:@"previewUrl"];
                NSString *trackViewUrl = [aResult valueForKey:@"trackViewUrl"];

Thanks anyway!

LP
