### ISSUE TITLE
BSD two-clause or three-clause license?

### ISSUE THREAD

**Issue by jhftrifork** [johnezang/JSONKit#163]
From `README.md`:

> JSONKit is dual licensed under either the terms of the BSD License, or alternatively under the terms of the Apache License, Version 2.0.

Does "the BSD License" refer to [the two-clause license](http://opensource.org/licenses/BSD-2-Clause) or [the three-clause license](http://opensource.org/licenses/BSD-3-Clause)?

I would like this disambiguated to ensure that I am conforming to the license of your choice. Ideally, could you include a `LICENSE` file in the repository, with the license text in it?

**Comment by Bo98** [comment]
The license text is in the source files themselves:

https://github.com/johnezang/JSONKit/blob/82157634ca0ca5b6a4a67a194dd11f15d9b72835/JSONKit.h#L8-L38

**Comment by jhftrifork** [comment]
Ah, I see, thanks! 3-clause license.
