### ISSUE TITLE
Build warning: 'calculateNumberHash' declared 'static' but never defined

### ISSUE THREAD

**Issue by edog1203** [johnezang/JSONKit#2]
With JSONKit HEAD as of 1/26/11:
JSONKit.m:356: warning: 'calculateNumberHash' declared 'static' but never defined

At first glance it looks safe to delete that line, but I wonder whether it's perhaps meant to be used somewhere (but isn't).

(Building with Xcode 3.2.5, iOS 4.2 SDK)

**Comment by johnezang** [comment]
Fixed v1.3
