### ISSUE TITLE
Missing @throw or incorrect method name

### ISSUE THREAD

**Issue by drodriguez** [johnezang/JSONKit#20]
As of 862fa4dbd0362bad859d, line 2793 reads like this:

```
if((encodeState = (struct JKEncodeState *)calloc(1UL, sizeof(JKEncodeState))) == NULL) { [NSException exceptionWithName:NSMallocException reason:@"Unable to allocate state structure." userInfo:NULL]; return(NULL); }
```

That, in case of a memory problem will create the exception object and not do anything with it. I think is missing a @throw statement, or creating the exception using a `+[NSException raise:format:]` method (like is done in the rest of the file).

```
[NSException raise:NSMallocException format:@"Unable to allocate state structure."]
```

**Comment by johnezang** [comment]
Not sure how this happened.  I'm going to blame autocompletion.  :)
