### ISSUE TITLE
Crash when creating -mutableCopy of parse result, then releasing the copy

### ISSUE THREAD

**Issue by edog1203** [johnezang/JSONKit#3]
1) Parse JSON in NSData format by calling -objectFromJSONData
2) Invoke -mutableCopy on the result
3) Release (or autorelease) the result of -mutableCopy

The application will crash in JSONKit code. The crash point is as follows:

Thread 0 Crashed:  Dispatch queue: com.apple.main-thread
0   CoreFoundation                  0x00e8b057 **_forwarding**_ + 183
1   CoreFoundation                  0x00e8af22 _CF_forwarding_prep_0 + 50
2   CoreFoundation                  0x00e30a6c CFRelease + 92
3   CrashJSONKit                    0x00001e7d jk_CFCallbackRelease + 17 (JSONKit.m:312)
4   CoreFoundation                  0x00e53b22 __CFArrayReleaseValues + 178
5   CoreFoundation                  0x00e30bcb _CFRelease + 251
6   CoreFoundation                  0x00e55b8d _CFAutoreleasePoolPop + 237
7   Foundation                      0x0001f443 -[NSAutoreleasePool release] + 167
8   UIKit                           0x002d0bf2 _UIApplicationHandleEvent + 8792
9   GraphicsServices                0x0184fa36 PurpleEventCallback + 1550

I've created a minimal sample project which exhibits the crash. The above code is all that exists in it other than standard app setup code. It doesn't have any strange build flags or link against any non-vanilla frameworks.

Download the sample project at: http://dl.dropbox.com/u/102780/CrashJSONKit.zip

This is on Xcode 3.2.5 against iOS SDK 4.2.

**Comment by johnezang** [comment]
Fixed in version 1.3.
