### ISSUE TITLE
Crash when parsing empty (but valid) JSON "{}"

### ISSUE THREAD

**Issue by jeremyellison** [johnezang/JSONKit#31]
JSONKit crashes when parsing the string "{}" with a divide by zero error. The following change has fixed the issue for me:

--- a/Vendor/JSONKit/JSONKit.m
+++ b/Vendor/JSONKit/JSONKit.m
@@ -1005,7 +1005,8 @@ static void _JKDictionaryAddObject(JKDictionary *dictionary, NSUInteger keyHash,

 static JKHashTableEntry *_JKDictionaryHashTableEntryForKey(JKDictionary *dictionary, id aKey) {
   NSCParameterAssert((dictionary != NULL) && (dictionary->entry != NULL) && (dictionary->count <= dictionary->capacity));
-  if(aKey == NULL) { return(NULL); }
-  // Guard against a divide by zero here.
-  if(aKey == NULL || 0 == dictionary->capacity) { return(NULL); }
  NSUInteger        keyHash = CFHash(aKey), keyEntry = (keyHash % dictionary->capacity), idx = 0UL;
  JKHashTableEntry *atEntry = NULL;
  for(idx = 0UL; idx < dictionary->capacity; idx++) {

**Comment by johnezang** [comment]
This bug was fixed in commit johnezang/JSONKit@18a0a3a4937d908a48d453a75ca9b92fc1d20d9b.
