### ISSUE TITLE
where to find clean copy for 10.7 and iOS5

### ISSUE THREAD

**Issue by oprisk** [johnezang/JSONKit#32]

**Comment by johnezang** [comment]
What do you mean by "clean copy for 10.7 and iOS5"?  You'll need to provide more details.

**Comment by oprisk** [comment]
Thanks for the quick feedback. The question pertains to iOS5 / 10.7 Lion preview 4 version release.  
The current available version of JSONKit does not clean compile in XCode, and given the Apple NDA associated with the release, I'm prevented from directly discussing the issues.  I ask for help locating a version upgraded to work under iOS5.
Thanks

**Comment by johnezang** [comment]
You can send me a private message directly if you'd like to discuss something non-publically.  You can do so by clicking on my name, @johnezang, to get my GitHub profile page.  There should be a button near the top that says "Message".  As you can imagine, without knowing the specifics of your problem, it's difficult for me to help you.  :)

**Comment by johnezang** [comment]
The issue encountered by @oprisk was related to the new [Objective-C Automatic Reference Counting (ARC)](http://clang.llvm.org/docs/AutomaticReferenceCounting.html) feature that was covered by NDA (which has [recently been lifted](http://lists.cs.uiuc.edu/pipermail/cfe-dev/2011-June/015588.html)).

I have updated (johnezang/JSONKit@c2146ffeb10d92bfa1537d2033a3235825d1b261) the `README.md` with a note that JSONKit does not support [ARC](http://clang.llvm.org/docs/AutomaticReferenceCounting.html)  and added a pre-processor check to `JSONKit.m` to throw an `#error` if it detects `JSONKit.m` is being compiled with `-fobjc-arc`.
