### ISSUE TITLE
Benchmark against NSJSONSerialization

### ISSUE THREAD

**Issue by marcetcheverry** [johnezang/JSONKit#39]
Do an updated benchmark against NSJSONSerialization.

**Comment by soffes** [comment]
I have benchmarked this in the 5.0 branch of my [JSON Benchmarks](https://github.com/samsoffes/json-benchmarks/tree/5.0) project. JSONKit beats NSJSONSerialization.

Feel free to download and try it.

**Comment by johnezang** [comment]
Added a note to `README.md` to a site (http://www.bonto.ch/blog/2011/12/08/json-libraries-for-ios-comparison-updated/) that benchmarks `NSJSONSerialization` and JSONKit.
