### ISSUE TITLE
Serialize NSMutableData

### ISSUE THREAD

**Issue by jasonmgeorge** [johnezang/JSONKit#42]
It may be a user error, but I am unable serialize a dictionary containing an MSMutableData object.

When attempting to do so, I get

Error Domain=JKErrorDomain Code=-1 "Unable to serialize object class NSConcreteMutableData." UserInfo=0x4c31b50 {NSLocalizedDescription=Unable to serialize object class NSConcreteMutableData.}

**Comment by jasonmgeorge** [comment]
NSData fails similarly with an NSConcreteData error

**Comment by johnezang** [comment]
This is not a bug in JSONKit, the documentation clearly states what types of objects JSONKit will serialize and that all other object classes will cause an error.

If you need to "easily" serialize `NSData` objects, I would suggest looking at the `master` branch code that allows you to dynamically catch object classes that JSONKit does not automatically serialize and transform them in to a type that it does.  By far the most common approach for `NSData` would to to turn the `NSData` in to a `Base64` encoded `NSString`.

**Comment by jasonmgeorge** [comment]
Works beautifully! Thanks!
