### ISSUE TITLE
Crash on empty dictionary when trying to get a value in it

### ISSUE THREAD

**Issue by jasongregori** [johnezang/JSONKit#48]
I'm getting a crash in the `_JKDictionaryHashTableEntryForKey` function on this line:

```
NSUInteger        keyHash = CFHash(aKey), keyEntry = (keyHash % dictionary->capacity), idx = 0UL;
```

I was calling `valueForKeyPath:` on a dictionary I got out of JSONKit that happened to have no entries. I think it's crashing because it's trying to mod the keyHash with zero.

**Comment by jasongregori** [comment]
Possible fix is changing the line before to:

```
  if(aKey == NULL || dictionary->capacity == 0) { return(NULL); }
```

But maybe you can think of a more elegant solution.

**Comment by johnezang** [comment]
This is almost certainly a dupe of #31 and #38.

**Comment by jasongregori** [comment]
You're right, sorry!
