### ISSUE TITLE
can not deserialize single number

### ISSUE THREAD

**Issue by groue** [johnezang/JSONKit#49]
Hello, shouldn't JSONKit deserialize a single number ?

Here is the error I get when I provide the single digit 1 to JSONKit:

```NSError *error;
    NSData *data = [@"1" dataUsingEncoding:NSUTF8StringEncoding];
    id object = [data objectFromJSONDataWithParseOptions:JKParseOptionStrict error:&error];

``````

```(gdb) po object
Can't print the description of a NIL object.
(gdb) po error
Error Domain=JKErrorDomain Code=-1 "Invalid number." UserInfo=0x5b076a0 {JKAtIndexKey=1, JKLineNumberKey=1, NSLocalizedDescription=Invalid number.}
``````

**Comment by johnezang** [comment]
No, a single number, as in your example, is not valid JSON.

**Comment by groue** [comment]
All right. http://www.json.org/ would need people like you to make things unambiguous.

**Comment by johnezang** [comment]
When in doubt, you can use http://jsonlint.com/ .  In order for it to be valid JSON, it must "start" with either a `{` or `[`, which is to say the JSON must be a `JSON Object` (i.e., `NSDictionary`), or a `JSON Array` (i.e., `NSArray`).

So, `[1]`, would be valid JSON, but a bare `1` by itself is not.

**Comment by groue** [comment]
Thanks, for these answers, and the very good JSONKit :-)
