### ISSUE TITLE
NSNull -> nil

### ISSUE THREAD

**Issue by samvermette** [johnezang/JSONKit#7]
Any plan on supporting this like TouchJSON and other parsers do? For now I've added an NSDictionary category that checks for null values and return nil instead. I've tried adding that directly to the parser but that code is way beyond my knowledge ^^

**Comment by johnezang** [comment]
No.  That isn't a feature, it's a bug.  If TouchJSON is actually doing that, you should file a bug with that project `NSNull` is `!=` to `nil` for a very, **_very**_ good reason, and you should never treat it as if it was `==`.

http://developer.apple.com/library/mac/#documentation/Cocoa/Conceptual/NumbersandValues/Articles/Null.html%23//apple_ref/doc/uid/TP40005153-SW1

**Comment by odyth** [comment]
@johnezang, I disagree that it is a bug.  While NSNull is not equal to nil, they both mean the absence of a value.  A convenience of omitting them from the decoded dictionary is that you dont have to do both an Object comparison as well as a nil comparison to ensure your value is not in the dictionary.

**Comment by drunkhacker** [comment]
@odyth agree. That's not a bug. NSNull should be converted to nil
