### ISSUE TITLE
Unable to parse JSON with apostrophe instead of quote

### ISSUE THREAD

**Issue by rfurno** [johnezang/JSONKit#75]
Given a doc like with single quotes surrounding the key (instead of double quotes)
{'key':'abc'}
The parser will fail with the message: "Unexpected token, wanted '{', '}', '[', ']', ',', ':', 'true', 'false', 'null', '\"STRING\"', 'NUMBER'."

**Comment by kgn** [comment]
Single quotes are invalid JSON
