### ISSUE TITLE
float/double conversion

### ISSUE THREAD

**Issue by ghost** [johnezang/JSONKit#80]
-- edit withdraw

having a plist 

[key]freq[/key]
[real]0.6[/real]

json export:

"freq":0.59999999999999998

expected

"freq":0.6
# NO BUG

apple does the same thing , annoying, math rounding sucks

**Comment by odyth** [comment]
I was having this same error, where my jason had the value 99.99 and I ended up with 99.989999999999.  The error seems to be this line:

(void *)CFNumberCreate(NULL, kCFNumberDoubleType,   &parseState->token.value.number.doubleValue); 

I found though that if you change it from doubles to floats it works as expected.

(void *)CFNumberCreate(NULL, kCFNumberFloatType,   &parseState->token.value.number.floatValue);       produces 99.99 and in your example above 0.6
