### ISSUE TITLE
Cannot parse root JSON element that aren't array or object

### ISSUE THREAD

**Issue by avrahamshukron** [johnezang/JSONKit#85]
If I have a JSON that is not a structure (array or object) it is not parsed.
Is it a bug or is it the standard that requires that the root element will be a structure?

Examples:
<code>
1.4
"Just a string"
true
false
</code>

All of these failed to parse.

**Comment by johnezang** [comment]
JSONKit will only parse valid JSON, where valid JSON is defined by [RFC 4627](http://tools.ietf.org/html/rfc4627) (the JSON standard).  All valid JSON begins with either a `[` or a `{`.

You can use the [JSONLint](http://jsonlint.com/) web site to quickly check if something is valid JSON.
